function out1 = calculate_mass_velocities(L2,L3,L4,L2_dot,L3_dot,L4_dot,L_x,L_z,theta,theta_dot,x1_dot,z1_dot)
%CALCULATE_MASS_VELOCITIES
%    OUT1 = CALCULATE_MASS_VELOCITIES(L2,L3,L4,L2_dot,L3_dot,L4_dot,L_x,L_z,THETA,THETA_DOT,X1_DOT,Z1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Feb-2023 17:11:05

t2 = cos(theta);
t3 = sin(theta);
t4 = L_x.*t3.*theta_dot;
t5 = L_z.*t3.*theta_dot;
t6 = L_x.*t2.*theta_dot;
t7 = L_z.*t2.*theta_dot;
t8 = -t5;
t9 = -t6;
t10 = -t7;
out1 = [t4+t10+x1_dot+L2_dot.*t3+L2.*t2.*theta_dot,t4.*-2.0+t10+x1_dot+L3_dot.*t3+L3.*t2.*theta_dot,t4+t10+x1_dot+L4_dot.*t3+L4.*t2.*theta_dot,t8+t9+z1_dot-L2_dot.*t2+L2.*t3.*theta_dot,t6.*2.0+t8+z1_dot-L3_dot.*t2+L3.*t3.*theta_dot,t8+t9+z1_dot-L4_dot.*t2+L4.*t3.*theta_dot];
