function out1 = calculate_platform_velocities(L_x,L_z,theta,theta_dot,x1_dot,z1_dot)
%CALCULATE_PLATFORM_VELOCITIES
%    OUT1 = CALCULATE_PLATFORM_VELOCITIES(L_x,L_z,THETA,THETA_DOT,X1_DOT,Z1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Feb-2023 17:11:05

t2 = cos(theta);
t3 = sin(theta);
t4 = L_x.*t3.*theta_dot;
t5 = L_z.*t3.*theta_dot;
t6 = L_x.*t2.*theta_dot;
t7 = L_z.*t2.*theta_dot;
t8 = -t5;
t9 = -t6;
t10 = -t7;
t11 = t4+t10+x1_dot;
t12 = t8+t9+z1_dot;
out1 = [t11,t4.*-2.0+t10+x1_dot,t11,t12,t6.*2.0+t8+z1_dot,t12];
