function Fex_reg = excitation_force_regular_3DOF(F11_im,F11_re,F33_im,F33_re,F55_im,F55_re,h_wave,t,w_wave)
%excitation_force_regular_3DOF
%    Fex_reg = excitation_force_regular_3DOF(F11_im,F11_re,F33_im,F33_re,F55_im,F55_re,H_WAVE,T,W_WAVE)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Feb-2023 12:15:28

t2 = t.*w_wave;
t3 = cos(t2);
t4 = sin(t2);
Fex_reg = [h_wave.*(F11_im.*t4-F11_re.*t3).*(-1.0./2.0);h_wave.*(F33_im.*t4-F33_re.*t3).*(-1.0./2.0);h_wave.*(F55_im.*t4-F55_re.*t3).*(-1.0./2.0)];
