function right_hand_vector = calculate_right_hand_vector_heave_TID(C33,K33,L2,L3,L4,L5,L6,L7,L2_0,L3_0,L4_0,L5_0,L6_0,L7_0,L5_dot,L6_dot,L7_dot,c2,c3,c4,k2,k3,k4,k5,k6,k7,z1,z1_dot)
%calculate_right_hand_vector_heave_TID
%    RIGHT_HAND_VECTOR = calculate_right_hand_vector_heave_TID(C33,K33,L2,L3,L4,L5,L6,L7,L2_0,L3_0,L4_0,L5_0,L6_0,L7_0,L5_dot,L6_dot,L7_dot,C2,C3,C4,K2,K3,K4,K5,K6,K7,Z1,Z1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 23:17:35

t2 = L2.*2.0;
t3 = L3.*2.0;
t4 = L4.*2.0;
t5 = L5.*2.0;
t6 = L6.*2.0;
t7 = L7.*2.0;
t8 = L2_0.*2.0;
t9 = L3_0.*2.0;
t10 = L4_0.*2.0;
t11 = L5_0.*2.0;
t12 = L6_0.*2.0;
t13 = L7_0.*2.0;
t14 = -t5;
t15 = -t6;
t16 = -t7;
t17 = -t8;
t18 = -t9;
t19 = -t10;
t20 = t2+t11+t14+t17;
t21 = t3+t12+t15+t18;
t22 = t4+t13+t16+t19;
t23 = (k5.*t20)./2.0;
t24 = (k6.*t21)./2.0;
t25 = (k7.*t22)./2.0;
right_hand_vector = [-C33.*z1_dot-K33.*z1;-t23-(k2.*(t2+t17))./2.0;-t24-(k3.*(t3+t18))./2.0;-t25-(k4.*(t4+t19))./2.0;t23-L5_dot.*c2;t24-L6_dot.*c3;t25-L7_dot.*c4];
