function left_hand_matrix = calculate_left_hand_matrix_FD_TID(A33,C33,K33,b2,b3,b4,c2,c3,c4,j_w,k2,k3,k4,k5,k6,k7,m1,m2,m3,m4,w)
%calculate_left_hand_matrix_FD_TID
%    LEFT_HAND_MATRIX = calculate_left_hand_matrix_FD_TID(A33,C33,K33,B2,B3,B4,C2,C3,C4,J_W,K2,K3,K4,K5,K6,K7,M1,M2,M3,M4,W)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 23:17:41

t2 = w.^2;
t3 = -k5;
t4 = -k6;
t5 = -k7;
t6 = m2.*t2;
t7 = m3.*t2;
t8 = m4.*t2;
t9 = -t6;
t10 = -t7;
t11 = -t8;
left_hand_matrix = reshape([K33+t9+t10+t11-t2.*(A33./2.0+m1./2.0).*2.0+C33.*j_w.*w,t6,t7,t8,0.0,0.0,0.0,t6,k2+k5+t9,0.0,0.0,t3,0.0,0.0,t7,0.0,k3+k6+t10,0.0,0.0,t4,0.0,t8,0.0,0.0,k4+k7+t11,0.0,0.0,t5,0.0,t3,0.0,0.0,k5-b2.*t2+c2.*j_w.*w,0.0,0.0,0.0,0.0,t4,0.0,0.0,k6-b3.*t2+c3.*j_w.*w,0.0,0.0,0.0,0.0,t5,0.0,0.0,k7-b4.*t2+c4.*j_w.*w],[7,7]);
