function right_hand_vector = calculate_right_hand_vector_FD_TMD(L2_0,L3_0,L4_0,k2,k3,k4)
%calculate_right_hand_vector_FD_TMD
%    RIGHT_HAND_VECTOR = calculate_right_hand_vector_FD_TMD(L2_0,L3_0,L4_0,K2,K3,K4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 15:09:11

right_hand_vector = [0.0;L2_0.*k2;L3_0.*k3;L4_0.*k4];
