function left_hand_matrix = calculate_left_hand_matrix_FD_TMD(A33,C33,K33,c2,c3,c4,j_w,k2,k3,k4,m1,m2,m3,m4,w)
%calculate_left_hand_matrix_FD_TMD
%    LEFT_HAND_MATRIX = calculate_left_hand_matrix_FD_TMD(A33,C33,K33,C2,C3,C4,J_W,K2,K3,K4,M1,M2,M3,M4,W)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 15:09:11

t2 = w.^2;
t3 = m2.*t2;
t4 = m3.*t2;
t5 = m4.*t2;
t6 = -t3;
t7 = -t4;
t8 = -t5;
left_hand_matrix = reshape([K33+t6+t7+t8-t2.*(A33./2.0+m1./2.0).*2.0+C33.*j_w.*w,t3,t4,t5,t3,k2+t6+c2.*j_w.*w,0.0,0.0,t4,0.0,k3+t7+c3.*j_w.*w,0.0,t5,0.0,0.0,k4+t8+c4.*j_w.*w],[4,4]);
