function right_hand_vector = calculate_right_hand_vector_FD_TID(L2_0,L3_0,L4_0,L5_0,L6_0,L7_0,k2,k3,k4,k5,k6,k7)
%calculate_right_hand_vector_FD_TID
%    RIGHT_HAND_VECTOR = calculate_right_hand_vector_FD_TID(L2_0,L3_0,L4_0,L5_0,L6_0,L7_0,K2,K3,K4,K5,K6,K7)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 23:17:41

t2 = L2_0.*2.0;
t3 = L3_0.*2.0;
t4 = L4_0.*2.0;
t5 = L5_0.*2.0;
t6 = L6_0.*2.0;
t7 = L7_0.*2.0;
t8 = -t5;
t9 = -t6;
t10 = -t7;
t11 = t2+t8;
t12 = t3+t9;
t13 = t4+t10;
t14 = (k5.*t11)./2.0;
t15 = (k6.*t12)./2.0;
t16 = (k7.*t13)./2.0;
right_hand_vector = [0.0;t14+L2_0.*k2;t15+L3_0.*k3;t16+L4_0.*k4;-t14;-t15;-t16];
