function U = calculate_potential_energy_TID(L2,L3,L4,L5,L6,L7,L2_0,L3_0,L4_0,L5_0,L6_0,L7_0,k2,k3,k4,k5,k6,k7)
%calculate_potential_energy_TID
%    U = calculate_potential_energy_TID(L2,L3,L4,L5,L6,L7,L2_0,L3_0,L4_0,L5_0,L6_0,L7_0,K2,K3,K4,K5,K6,K7)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Feb-2023 17:55:09

t2 = -L2_0;
t3 = -L3_0;
t4 = -L4_0;
U = (k5.*(L2-L5+L5_0+t2).^2)./2.0+(k6.*(L3-L6+L6_0+t3).^2)./2.0+(k7.*(L4-L7+L7_0+t4).^2)./2.0+(k2.*(L2+t2).^2)./2.0+(k3.*(L3+t3).^2)./2.0+(k4.*(L4+t4).^2)./2.0;
