function T = calculate_kinetic_energy_heave_TMD(A33,L2_dot,L3_dot,L4_dot,m1,m2,m3,m4,z1_dot)
%calculate_kinetic_energy_heave_TMD
%    T = calculate_kinetic_energy_heave_TMD(A33,L2_dot,L3_dot,L4_dot,M1,M2,M3,M4,Z1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 15:09:10

t2 = -z1_dot;
T = z1_dot.^2.*(A33./2.0+m1./2.0)+(m2.*(L2_dot+t2).^2)./2.0+(m3.*(L3_dot+t2).^2)./2.0+(m4.*(L4_dot+t2).^2)./2.0;
