function T = calculate_kinetic_energy_TMD(J1,J2,J3,J4,L2,L3,L4,L2_dot,L3_dot,L4_dot,L_x,L_z,m1,m2,m3,m4,theta,theta_dot,x1_dot,z1_dot)
%calculate_kinetic_energy_TMD
%    T = calculate_kinetic_energy_TMD(J1,J2,J3,J4,L2,L3,L4,L2_dot,L3_dot,L4_dot,L_x,L_z,M1,M2,M3,M4,THETA,THETA_DOT,X1_DOT,Z1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Feb-2023 17:10:31

t2 = cos(theta);
t3 = sin(theta);
t4 = theta_dot.^2;
t5 = -z1_dot;
t6 = L_x.*t3.*theta_dot;
t7 = L_z.*t3.*theta_dot;
t8 = L_x.*t2.*theta_dot;
t9 = L_z.*t2.*theta_dot;
t10 = -t9;
T = (J1.*t4)./2.0+(J2.*t4)./2.0+(J3.*t4)./2.0+(J4.*t4)./2.0+(m3.*(-t7+t8.*2.0+z1_dot-L3_dot.*t2+L3.*t3.*theta_dot).^2)./2.0+(m2.*(t5+t7+t8+L2_dot.*t2-L2.*t3.*theta_dot).^2)./2.0+(m4.*(t5+t7+t8+L4_dot.*t2-L4.*t3.*theta_dot).^2)./2.0+(m2.*(t6+t10+x1_dot+L2_dot.*t3+L2.*t2.*theta_dot).^2)./2.0+(m4.*(t6+t10+x1_dot+L4_dot.*t3+L4.*t2.*theta_dot).^2)./2.0+(m1.*x1_dot.^2)./2.0+(m1.*z1_dot.^2)./2.0+(m3.*(t6.*-2.0+t10+x1_dot+L3_dot.*t3+L3.*t2.*theta_dot).^2)./2.0;
