function T = calculate_kinetic_energy_heave_TID(A33,L2_dot,L3_dot,L4_dot,L5_dot,L6_dot,L7_dot,b2,b3,b4,m1,m2,m3,m4,z1_dot)
%calculate_kinetic_energy_heave_TID
%    T = calculate_kinetic_energy_heave_TID(A33,L2_dot,L3_dot,L4_dot,L5_dot,L6_dot,L7_dot,B2,B3,B4,M1,M2,M3,M4,Z1_DOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Feb-2023 23:17:39

t2 = -z1_dot;
T = z1_dot.^2.*(A33./2.0+m1./2.0)+(m2.*(L2_dot+t2).^2)./2.0+(m3.*(L3_dot+t2).^2)./2.0+(m4.*(L4_dot+t2).^2)./2.0+(L5_dot.^2.*b2)./2.0+(L6_dot.^2.*b3)./2.0+(L7_dot.^2.*b4)./2.0;
